In [1]:
from arcgis import GIS

In [2]:
map=GIS().map("USA")
map

MapView(layout=Layout(height='400px', width='100%'))

In [3]:
map=GIS().map("COLOMBIA")
map

MapView(layout=Layout(height='400px', width='100%'))

In [4]:
map=GIS().map("BOGOTA")
map

MapView(layout=Layout(height='400px', width='100%'))

In [2]:
import numpy as np
import pandas as pd
import scipy as sp

In [6]:
s = pd.Series([1, 3, 5, np.nan, 6, 8])
print("Mi serie es:\n")
print(s)

Mi serie es:

0    1.0
1    3.0
2    5.0
3    NaN
4    6.0
5    8.0
dtype: float64


In [7]:
# Individuos (Fechas)
# M = Month end Frequency 
dates = pd.date_range('20130101', periods=6,freq='M')

In [8]:
# Showing horizontally
print(dates)
print("\n Showing Vertically:\n")

# Showing Vertically
for date in dates:
    print(date)

DatetimeIndex(['2013-01-31', '2013-02-28', '2013-03-31', '2013-04-30',
               '2013-05-31', '2013-06-30'],
              dtype='datetime64[ns]', freq='M')

 Showing Vertically:

2013-01-31 00:00:00
2013-02-28 00:00:00
2013-03-31 00:00:00
2013-04-30 00:00:00
2013-05-31 00:00:00
2013-06-30 00:00:00


In [9]:

A=np.random.randn(6, 4)
print(A)

[[-0.08242401 -0.36726209 -0.17440699  0.75850873]
 [ 1.10523276 -1.51448639  1.22286582  0.10640415]
 [ 0.60911364  2.03944843  1.25761564  2.2137961 ]
 [-0.66399495 -1.74206671  0.7981953  -0.11366909]
 [-0.86152718  0.70972786  1.65893629 -0.7342993 ]
 [ 0.52274408 -0.77440356 -0.92319023 -0.31569239]]


In [10]:
variables=list("ABCD")

In [11]:
df1 = pd.DataFrame(A, index=dates, columns=variables)

In [12]:
df1

A         B         C         D
2013-01-31 -0.082424 -0.367262 -0.174407  0.758509
2013-02-28  1.105233 -1.514486  1.222866  0.106404
2013-03-31  0.609114  2.039448  1.257616  2.213796
2013-04-30 -0.663995 -1.742067  0.798195 -0.113669
2013-05-31 -0.861527  0.709728  1.658936 -0.734299
2013-06-30  0.522744 -0.774404 -0.923190 -0.315692

In [14]:

df=pd.read_csv("./data/El colegio Prec.csv")

FileNotFoundError: [Errno 2] File b'./data/El colegio Prec.csv' does not exist: b'./data/El colegio Prec.csv'

In [15]:
df.head()

NameError: name 'df' is not defined

In [1]:
nj_bounds = nj_boundary.layers[0].query(out_sr=4325,as_df=True)
geon = nj_bounds.iloc[0].SHAPE
geom

NameError: name 'nj_boundary' is not defined

In [12]:
from arcgis import GIS
gis = GIS()
# create an anonymous connection to ArcGIS Online and get a public item
item = gis.content.get("9c98c1a905264f6d9ed72712fe9b2f2b")
#item = gis.content.get("85d0ca4ea1ca4b9abf0c51b9bd34de2e")
flayer = item.layers[0]

# Specify a SQL query and get a sub-set of the original data as a DataFrame
df = flayer.query(where="ESTACIÓN").sdf

# Visualize the top 5 records
df.head()


'where' parameter is invalid


RuntimeError: 
'where' parameter is invalid
(Error Code: 400)

In [6]:
m1 = GIS().map('United States')
m1

MapView(layout=Layout(height='400px', width='100%'))

In [8]:
m1 . zoom  =  4 
m1 . centro  =  [ 39 , - 98 ]

In [9]:
df.spatial.plot(map_widget= m1)

True

In [10]:
m2= GIS().map('United States', zoomlevel=4)
m2

MapView(layout=Layout(height='400px', width='100%'), zoom=4.0)

In [11]:
m2.center=[39,-98]
df.spatial.plot(map_widget=m2,
            symbol_type='simple',
            symbol_style='d', # d - for diamonds
            colors='Reds_r',
            cstep=10,
            outline_color='Blues',
            marker_size=10)

True